controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names:  ["joint_FL", "joint_ML", "joint_BL"]
    right_wheel_names: ["joint_FR", "joint_MR", "joint_BR"]
    wheel_separation: 0.37
    wheel_radius: 0.075
    base_frame_id: base_footprint
    odom_frame_id: odom
    publish_rate: 50.0
    enable_odom_tf: true
    use_stamped_vel: false
    open_loop: false